version: '3.8'

services:

  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "8081:16686"  # Jaeger UI
      - "14268"
      - "14250"

  otel-collector:
    image: otel/opentelemetry-collector:latest
    container_name: otel-collector
    command: ["--config=/etc/otel-collector-config.yml"]
    volumes:
      - ./otel-collector-config.yml:/etc/otel-collector-config.yml
    ports:
      - "1888:1888"   # pprof extension
      - "13133:13133" # health_check extension
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # http gRPC receiver
      - "55679:55679" # zpages extension
    depends_on:
      - jaeger
    links:
      - jaeger

  mail:
    image: maildev/maildev
    container_name: mail
    ports:
      - "1080:1080"   # Interface web
      - "1025:1025"   # SMTP

volumes:
  mysql_data: